### ISSUE TITLE
Unable to install rubysl-pty on Windows 10

### ISSUE THREAD

**Issue by apanimesh061** [rubysl/rubysl-pty#9]
I am currently using `ruby-2.3.1`.

I have to run `napa` on my system but I get the following error when I start it.

```
Napa server starting...
E:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file -- pty (LoadError)
        from E:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from E:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/napa-0.5.0/lib/napa/cli/base/server.rb:10:in `server'
        from E:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from E:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from E:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from E:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from E:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/napa-0.5.0/bin/napa:5:in `<top (required)>'
        from E:/Ruby23-x64/bin/napa:23:in `load'
        from E:/Ruby23-x64/bin/napa:23:in `<main>'
```

So, I read that `pty` does not run on Windows so we can use `rubysyl-pty` instead which requires `DevKit`. But I am still for able to install it:

```
E:\Ruby23-x64\DevKit>ruby dk.rb init
[INFO] found RubyInstaller v2.3.1 at E:/Ruby23-x64

Initialization complete! Please review and modify the auto-generated
'config.yml' file to ensure it contains the root directories to all
of the installed Rubies you want enhanced by the DevKit.

E:\Ruby23-x64\DevKit>ruby dk.rb review
Based upon the settings in the 'config.yml' file generated
from running 'ruby dk.rb init' and any of your customizations,
DevKit functionality will be injected into the following Rubies
when you run 'ruby dk.rb install'.

E:/Ruby23-x64

E:\Ruby23-x64\DevKit>ruby dk.rb install
[INFO] Skipping existing gem override for 'E:/Ruby23-x64'
[WARN] Skipping existing DevKit helper library for 'E:/Ruby23-x64'

E:\Ruby23-x64\DevKit>gem install rubysl-pty --platform=ruby
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing rubysl-pty:
        ERROR: Failed to build gem native extension.

    current directory: E:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubysl-pty-2.0.3/ext/rubysl/pty
E:/Ruby23-x64/bin/ruby.exe -r ./siteconf20161014-3752-rli5pg.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=E:/Ruby23-x64/bin/$(RUBY_BASE_NAME)

extconf failed, exit code 1

Gem files will remain installed in E:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubysl-pty-2.0.3 for inspection.
Results logged to E:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/rubysl-pty-2.0.3/gem_make.out
```

I am adding my `GemFile` to the post for reference:

```
source 'http://rubygems.org'
ruby "2.3.1"

gem 'rack-cors'
gem 'mysql2'
gem 'activerecord', '~> 4.2.0', :require => 'active_record'
gem 'hashie-forbidden_attributes'
gem 'honeybadger', '~> 1.16.7'
gem 'json'
gem 'napa', '~> 0.5.0'
gem 'roar', '~> 0.12.0'
gem 'grape-swagger'

group :development,:test do
  gem 'pry'
end

group :development do
  gem 'rubocop', require: false
  gem 'shotgun', require: false
end

group :test do
  gem 'factory_girl'
  gem 'rspec'
  gem 'rack-test'
  gem 'simplecov'
  gem 'webmock'
  gem 'database_cleaner'
  gem 'shoulda-matchers'
end
```

**Comment by chuckremes** [comment]
We have very little experience getting Rubinius or any of the rubysl projects running on Windows. We would like your help in figuring it out

**Comment by apanimesh061** [comment]
I figured out the issue. It was that windows did not have `make` installed, as a result of which it could not create a `MakeFile`.
Right now I am able to install `rubysl-pty-2.0.3.gem` on `ruby 2.2.5p319` on Windows after reinstalling `Cygwin`.
